# 31강. 기본적인 예외처리 방법

## C++의 예외 처리 매커니즘

- 예외 상황 검사 - 예외 발생 - 예외 처리
    - try 블럭
        - 예외 발생 여부를 검사할 코드의 묶음
        - throw 문으로 예외 처리 매커니즘을 구동 위해 예외를 던짐
    - catch 블럭
        - 던져진(발생된) 예외를 받아 처리
- 장점
    - 코드 상에서 정상 상태(try)와 예외 상태(catch)를 명로하게 구분 가능
    - 예외가 발생한 이후의 코드에 대해 신경 쓸 필요가 줄어든다.

## 예외 처리 기본 형식

```cpp
try {
	...
	if (예외 상황1을 발견) {
		throw 예외 값1;
	}
	...
	if (예외 상황2를 발견) {
		throw 예외 값 2;
	}
	...
}
catch (처리할 예외 파라미터 선언) {
	예외 상황 1에 대한 처리문;
}
catch (처리할 예외 파라미터 선언) {
	예외 상황2에 대한 처리문;
}
```

## try 블록

- 예외가 발생할 가능성이 있는 문장과 그와 연관된 문장들을 위치 시킴
- 예외 발생을 탐지하는 코드를 포함
    - 예외 상황이 탐지되면 throw 문을 실행하여 예외 발생을 알림
- 예외 발생 시, 예외를 발생시킨 문장 다음의 문장들은 처리되지 않음

## throw 문

```cpp
throw 예외 값;
```

- 예외 상황이 발생됨을 알림
    - 보통 try 블록 안에서 실행
    - 정상적인 흐름은 중단되고 예외 상황에 대한 처리 과정이 수행됨
    - 예외를 던진다
        - 예외는 예외 값을 가짐
- 던져진 예외는 연결된 catch 블록에서 처리됨
    - 연결된 catch 블록이 없으면 프로그램 강제 종료

## catch 블록

- throw에 의해 발생한 예외를 처리하는 코드들
    - 하나의 try 블록에 여러 개의 catch 블록이 올 수 있음
        - 각 catch 블록은 자료형에 따라 하나의 예외만 처리
            - 자료형 기술대신 ‘…’라 쓰면 모든 예외를 받을 수 있음
        - 던져진 예외 값을 받을 수 있는 매개 변수를 갖는 catch 블록이 수행됨
    
    ```cpp
    try {
    	...
    	throw 3;
    	...
    }
    catch (int x) {
    	...
    }
    ```
    

## 예제 예외 처리 과정

```cpp
try {
	// n = 5
	if (n == 0)
		throw n;
	else {
		avg = sum / n;
		...
		cout << "평균 = " << avg << endl;
	}
}
catch (int x) {
		cout << "예외 발생!!";
		cout << x << "으로 나눌 수 없음" << endl;
}

cout << "종료!" << endl;
/*
평균 = 3
종료!
*/
```

```cpp
try {
	// n = 0
	if (n == 0)
		throw n;
	else {
		avg = sum / n;
		...
		cout << "평균 = " << avg << endl;
	}
}
catch (int x) {
		cout << "예외 발생!!";
		cout << x << "으로 나눌 수 없음" << endl;
}

cout << "종료!" << endl;
/*
예외 발생!! 0으로 나눌 수 없음
종료!
*/
```

## 다수의 catch 블록

- c++는 예외 객체가 따로 존재하지는 않음
- 보통 기본 자료형의 데이터를 던지게 된다
- 던져진 예외 값이 자료형과 일치하는 catch 블록이 예외 값을 받음

```cpp
try {
	...
	throw "음수 불가능";
	...
	throw 3;
}
catch (const char* s) { // s에 "음수 불가능"이 전달
	...
}	
catch (int x) {// x에 3이 전달
	...
}
catch (...) {
	cerr << "모든 예외를 받는 catch 절" << endl;
}
```